### ISSUE TITLE
ECCV 2024 LSVOS challenge

### ISSUE THREAD

**Issue by bhack** [yahooo-m/VOS-Solution#1]
Do you plan to submit something also for the 6th LSVOS challenge?

https://lsvos.github.io/

**Comment by yahooo-m** [comment]
Yes, we also plan to test our method for the 6th LSVOS Challenge.

**Comment by bhack** [comment]
Do you plan to have a code release?

**Comment by yahooo-m** [comment]
We will release the code after the acceptation of the paper. Thanks for waiting~
